"""Mercedes-Benz terminology rules extracted from internal workbook.
Generated from: Mercedes-Benz executive list-internal.xlsx

This v1 file is designed for direct import into a PR Agent project.
Use it first for normalize/check/rewrite. The executive list is included as a lightweight lookup,
but should still be reviewed manually before being used for auto-replacement.
"""

# Core terminology dictionaries
MB_CN_TO_EN = {'电驱单元（EDU）': 'Electric Drive Unit (EDU)',
 '两级弹性轴承': 'two elastomer bearing levels',
 '双重隔音结构': 'double structure-borne noise',
 '800伏电气架构': '800-volt electric architecture',
 '多源热泵系统': 'multi-source heat pump',
 '电气化双离合变速箱（eDCT）': 'Electric dual clutchless transmission (eDCT)',
 '碳化硅逆变器': 'SiC (Silicon Carbide) Inverter',
 '四驱断开装置 (DCU)': 'Disconnect Unit (DCU)',
 'OneBox制动系统': 'OneBox braking system',
 '两挡变速箱': 'two-speed gearbox / two-speed transmission',
 '电气化8速双离合变速箱': '8F-eDCT',
 '米勒循环': 'Miller combustion process',
 'NANOSLIDE®缸壁镀膜技术': 'NANOSLIDE® technology',
 '全铝合金曲轴箱': 'all-aluminium crankcase',
 '启停功能': 'start-stop function',
 '可用容量': 'usable energy content',
 '电池容量': 'energy content',
 '磷酸铁锂电池': 'battery with lithium-iron phosphate cathodes (LFP)',
 '锂离子电池': 'battery with lithium-ion technology',
 '镍钴锰三元锂电池': 'Nickel-manganese-cobalt (NMC)',
 '剩余电量百分比': 'battery SoC',
 '应急供电': 'vehicle-to-home',
 '向电网反向供电': 'vehicle-to-grid',
 '双向直流充电墙盒': 'bidirectional DC wallbox',
 '扁平式设计': 'flat-pack design',
 '液冷系统': 'liquid cooling system',
 '永磁同步电机': 'PSM (Permanent Magnet Synchronous Machine)',
 '定子绕组': 'winding of the stator',
 '重稀土': 'heavy rare earths',
 'D+无能量回收模式': 'D +',
 'DAuto智能能量回收模式': 'D Auto',
 '标准能量回收': 'D standard recuperation',
 '加强能量回收': 'D- increased recuperation',
 '节能辅助系统（ECO Assist）': 'ECO Assistant',
 '制动泵': 'Master cylinder',
 'MB.OS全新架构': 'Mercedes-Benz Operating System (MB.OS)',
 '梅赛德斯-奔驰智能云': 'Mercedes Benz Intelligent Cloud',
 '零层级界面': 'MBUX Zero Layer',
 'MBUX超级屏': 'MBUX Superscreen',
 'MBUX智能人机交互系统': 'Mercedes-Benz User Experience (MBUX)',
 '奔驰虚拟助手': 'MBUX Virtual Assistant',
 '全新MBUX沉浸式导航': 'MBUX Surround Navigation',
 'EQ优化导航': 'Mercedes-Benz navigation with Electric Intelligence',
 '自适应巡航ACC': 'DISTRONIC adaptive cruise control',
 '柱碰测试': 'pole impact test',
 '多级高压安全理念': 'multi-stage protection concept of the HV system',
 '整车系统测试台（FVS）': 'full vehicle system test bench',
 '滑板底盘': 'skateboard chassis',
 '梅赛德斯-奔驰模块化架构（MMA）平台': 'Mercedes-Benz Modular Architecture (MMA)',
 '智能模块化平台': 'intelligent modularity',
 '可扩展的滑板式设计': 'scalable skateboard design',
 '电动软件中心（ESH）': 'Electric Software Hub (ESH)',
 '梅赛德斯-奔驰技术中心（MTC）': 'Mercedes-Benz Technology Centre (MTC)',
 '梅赛德斯-奔驰事故研究部门': 'Mercedes-Benz Accident Research',
 '2039愿景': 'Ambition 2039',
 '“愿景承诺函”': 'Ambition Letter',
 '全面电动': 'Electric Only',
 '电动为先': 'Electric First',
 '星睿品牌': 'Star Elite',
 '星管家服务': 'Private Charging',
 '星随行': 'Public Charging',
 '星驿站': 'Brand Charging',
 '2050年零致命性交通事故愿景': 'vision of zero traffic fatalities by 2050',
 '“新豪华主义”产品体验': '"Modern Luxury" product',
 '“心豪华主义”服务体验': '"Premium Customer Care"',
 '可持续的发展之道': 'Sustainable Business Operation',
 '可持续的责任之道': 'Sustainable Development of Local Society via CSR Commitment',
 '商责并举': 'Sustainability in both business development and social responsibility',
 '“感性·纯粹”理念': '“Sensual Purity” concept',
 '限距控制系统': 'DISTRONIC',
 '限距控制系统增强版': 'DISTRONIC PLUS',
 '智能领航限距功能': 'Active Distance Assist DISTRONIC',
 '制动辅助系统增强版': 'BAS PLUS',
 '主动式车道保持辅助系统': 'Active Lane Keeping Assist',
 '自适应远光灯辅助系统增强版': 'Adaptive Highbeam Assist Plus',
 '夜视辅助系统增强版': 'Night View Assist Plus',
 '碰撞预防辅助系统增强版': 'COLLISION PREVENTION ASSIST PLUS',
 '自适应制动': 'ADAPTIVE BRAKE',
 '速度限制辅助系统': 'Speed Limit Assist',
 '车道保持辅助系统': 'Lane Keeping Assist',
 '注意力辅助系统': 'ATTENTION ASSIST',
 '预防性安全系统': 'PRE-SAFE®',
 'DRIVE PILOT驾驶领航系统': 'DRIVE PILOT (200)',
 'DRIVE PILOT驾驶领航组件': 'Driving assistant package with DRIVE PILOT (P26)',
 '智能变道及导航辅助驾驶': 'Automatic Lane Change （ALC）',
 '座椅侧碰保护功能': 'PRE-SAFE® Impulse Side.',
 '自适应巡航控制系统': 'adaptive cruise control',
 'CONISHAPE®缸壁珩磨': 'CONICSHAPE® cylinder honing',
 '视角限制功能': 'blanking function',
 'MBUX': 'MBUX智能人机交互系统',
 'MBUX读心语音助理功能': '"Hey Mercedes"',
 '读心感应助理': 'Magic Module',
 '畅心醒神自然主题': 'ENERGIZING NATURE programs',
 '畅心醒神功能': 'ENERGIZING COMFORT',
 '畅新空气护盾': 'ENERGIZING AIR CONTROL Plus',
 '雾霾终结者': 'ENERGIZING AIR CONTROL',
 '舒适模式': 'Comfort mode',
 '舒展模式': 'Freshness',
 '活力模式': 'Warmth',
 '自在模式': 'Vitality',
 '恬淡模式': 'Joy',
 '悠然模式': 'Comfort',
 '放松训练': 'Training',
 '总装车间': 'Assembly Shop',
 '装焊车间': 'Body Shop',
 '冲压车间': 'Stamping Shop',
 '生产车间经理': 'Workshop Manager',
 '主动式后轮转向系统': 'active rear-axle steering',
 '用户界面/用户体验': 'UI/UX',
 '主动制动辅助系统': 'Active Brake Assist',
 '主动车道保持辅助系统': 'Active Lane Keeping Assist',
 '全球首秀': 'World Premiere',
 '中国首秀': 'Chinese Premiere',
 '减振器': 'Continuous Damping Control',
 '人机交互': 'infotainment system',
 '台架实验室的建设规划': 'Dyno Planning',
 '卡车主减速器研发': 'Final-Drive-Development',
 '3.4S的百公里加速时间': 'the sprint time from 0-100km/h of 3.4s',
 '能量回收': 'energy recovery',
 '三叉星徽': 'the three-pointed star',
 '梅赛德斯-奔驰中国高级设计中心': 'Mercedes-Benz Advanced Design Center of China',
 '梅赛德斯-奔驰中国研发技术中心': 'TCC（Tech Center China）',
 '梅赛德斯-奔驰上海研发中心': 'Mercedes-Benz R&D Center Shanghai',
 '至臻豪华': 'Sophisticated Luxury',
 '性能豪华': 'Performance Luxury',
 '先锋豪华': 'Progressive Luxury',
 '拓界豪华': 'Adventurous Luxury',
 '主动式环境氛围灯': 'Active Ambient Lighting',
 'AMG垂瀑式封闭格栅': 'AMG-specific radiator grille',
 '阿法特巴赫': 'Affalterbach',
 '未来研习官': 'KLO-Knowledge Learning Officer',
 '插电式混合动力车型': 'plug-in hybrid model',
 '插电式混合动力车': 'plug-in hybrid electric vehicle (PHEV)',
 '纯电SUV': 'all-electric SUV',
 '越野能力': 'off-road capability',
 '中大型SUV': 'Mid-large SUV',
 '大型SUV': 'Large SUV',
 '五座': '5-seater',
 'OTA远程升级': 'Over-the-Air',
 '地球，我们心中的潘多拉星球': 'Earth is our Pandora.',
 '每一步都有意义。一同启程，共赴电动未来。': 'Every action counts. Join our journey to a fully electric future.',
 '带缓冲溃缩区与刚性乘员舱的安全车身': 'a safety body shell with a rigid passenger compartment and crumple zones at the front and rear',
 '到2050年实现“零致命性交通事故”': 'to achieve accident-free driving by 2050',
 '风阻': 'Wind resistance',
 '风阻系数': 'drag coefficient',
 '陡坡缓降功能': 'DSR (Downhill Speed Regulation)',
 'AMG徽章': 'AMG’s "Affalterbach" emblem',
 'AMG的“非凡驾驭”': 'AMG’s “Driving Performance"',
 'AMG主动行驶控制系统': 'ACTIVE RIDE CONTROL',
 '带自适应可调减振功能的AMG行驶控制增强版（AMG RIDE CONTROL+）空气悬挂': 'AMG RIDE CONTROL+ with air suspension, with adaptive controlled '
                                                 'adjustable damping',
 'AMG驾驶动态系统': 'AMG DYNAMICS/ AMG Dynamics',
 '动感模式': 'AMG Dynamics',
 '弹射起步': 'RACE START',
 'AMG驾驶动态控制系统': 'AMG DYNAMICS dynamic control system',
 'AMG 驾驶套件': "AMG Driver's Package",
 '电控车辆稳定行驶系统（ESP®）': 'Electronic Stability Program ESP®',
 '车身稳定性': 'rolling movement',
 '空气扩散器': 'air diffuser',
 '前裙板': 'front apron',
 '扰流板': 'Wheel spoilers / rear spoiler',
 '侧踏板': 'side sill panel',
 '智能气帘效果': 'AIR CURTAIN effect',
 '带镀铬饰边及高光黑色涂层的前分流器，进气口的翼片和风刀，以及左右两侧采用高光黑色涂层的空气扩散器': 'Front splitter in high-gloss black with chrome trim and flics '
                                                     'and fins on the air intakes. Air diffusers left and right in '
                                                     'high-gloss black',
 'AMG陶瓷高性能复合制动系统': 'AMG ceramic high-performance compound brake system',
 'AMG TRACK PACE虚拟竞赛工程师': 'AMG TRACK PACE',
 'AMG轻合金轮毂': 'AMG light-alloy wheels',
 'AMG高性能全时四轮驱动增强版': 'AMG Performance 4MATIC+ fully variable all-wheel drive',
 '哑光石墨灰色': 'graphite grey magno',
 '迈巴赫徽章/徽标': 'Maybach emblem',
 'Econyl再生尼龙材料': 'Econyl',
 '高端车系': 'Top End Vehicle (TEV)',
 '纯电车型': 'BEV (Battery Electric Vehicle)',
 '驾驶辅助组件增强版': 'Driving Assistance package Plus',
 '数字化风向调节': 'digital vent control',
 '璀璨星河木饰板 & 璀璨星雨数字大灯': 'trim & front light',
 '璀璨星环格栅': 'Front illuminated grill',
 '璀璨星芒尾灯': 'Rear light',
 '流星掠影光毯': 'Light carpet',
 '璀璨星河木饰板': 'Backlit trim',
 '360 ͦ环绕式环境氛围灯': 'Circumferential ambient light',
 '随音悦动': 'Sound visualisation',
 '璀璨星雨数字大灯': 'Front light',
 '沉浸式智享座舱': 'Overall interior',
 '筋线': 'powerdome',
 '经典先锋豪华': 'Iconic Luxury',
 '极夜版本（Night Series）': 'Maybach Night Series',
 '定义时代风潮': 'Defining Class since 1886',
 '全球首家L3、L4“双持证”车企': 'the world’s first automaker certified for Level 3 and Level 4 automated driving',
 '智能驾驶系统': 'intelligent driving assistance',
 '无论油电，都很奔驰': 'Powertrain varies, Mercedes is always a Mercedes',
 '“凡奢华美物，必有故事传承；凡奢华美物，必定表里如一；凡奢华美物，必将风格永存': 'Every luxury must have a story to pass on. Every luxury must be as '
                                            'sincerity as purity. Every luxury must last forever.',
 '卡尔·奔驰': 'Carl Benz',
 '中国研发 全球奔驰': 'RD in China for China and for the world',
 '在华发展 与华共进': 'Growing in China, with China',
 '中国制造、专属中国': 'developed in China, for China',
 '以中国创新，领全球风潮': 'Developed in China, innovating for the world',
 '虽非故土，亲似家园': 'China is our home away from home',
 '奔驰，一眼便知/ 一眼奔驰，风格始终': 'A Mercedes-Benz must always look like a Mercedes-Benz.',
 '智能驾驶辅助系统': 'driving assistance system',
 '自动驾驶系统': 'automated driving systems',
 '“数字雅座”': 'lounge concept',
 'EQ优化导航 改为 梅赛德斯-奔驰电动智能导航': 'navigation with Electric Intelligence ->Mercedes-Benz Navigation with Electric '
                            'Intelligence',
 '梅赛德斯-奔驰超级充电站': 'Mercedes-Benz branded high-power charging stations',
 '三电系统': 'e-Drive system',
 '热泵系统': 'heat pump',
 '奔驰的标准': 'Standards of Mercedes-Benz',
 '随行乐动': 'MBUX SOUND DRIVE',
 '智能车身控制（Magic Body Control）': 'Magic Body Control',
 '智能魔术车身控制系统（E-ACTIVE BODY CONTROL）': 'E-ACTIVE BODY CONTROL',
 'CN': 'EN',
 '纯电G级越野车 (7words, and “纯电” reflect “EQ Technology” properly)': 'W463 G-Class',
 '纯电G 580 (Ml Nov 2024)': 'G 350',
 '纯电G 580 先型特别版 (Ml July 2024)': 'G 500',
 'AMG.EA纯电架构平台': 'AMG.EA',
 'AMG高性能音浪': 'AMG Real Performance Sound',
 'G-ROAR 专属声浪': 'G-ROAR',
 '低速越野 （based on function）': 'Low range',
 '越野爬行 (based on function)': 'Offroad crawling',
 '扭矩矢量分配 (based on function)': 'Torque vectoring',
 '越野赛道 (based on function)': 'Offroad Track',
 '车尾装饰盒 (取代后边备胎轮毂罩，原本是放charging cable的，不过我们也不提供cable，其实就是一个塑料的小书包)': 'Design box',
 'MANUFAKTUR哑光澄海蓝色': 'MANUFAKTUR southsea blue magno',
 '发光星标': 'Illuminated Mercedes star',
 '叠影星空/ 流光星徽 / 璀璨星河 封闭式格栅': 'Panel with illuminated Mercedes-Benz pattern',
 '雾灰绿色': 'aqua-mint non-metallic',
 '晴空蓝色': 'Clear blue',
 '全景式天幕': 'Panoramic roof',
 '星辰轨迹 / 矩阵星轨 /星驰光轨 / 璀璨星轨 贯穿式尾灯': 'Rear light strip',
 '冷空灰': 'tech grey',
 'MBUX.超感屏 / MBUX.超级屏': 'Driver display',
 '嵌铝质饰条的棕色开孔型橡木饰条': "Ship's deck open-pore brown oak trim elements with aluminium lines",
 '灰色开孔型桦木木饰条': 'Open-pore grey birch wood trim elements',
 '哑光白色暗纹天然纤维饰条': 'Matt white natural fibre silent lines trim elements',
 'MB.Drive辅助驾驶': 'Digital Extra: MB.DRIVE ASSIST',
 'MB.Drive辅助驾驶Pro': 'Digital Extra: MB.DRIVE ASSIST PRO',
 '沉浸式导航': 'Digital Extra: MBUX Navigation',
 '梅赛德斯-奔驰电动智能导航': 'Mercedes-Benz Navigation with Electric Intelligence',
 '驻车守护': 'Digital Extra: GUARD 360° vehicle protection plus',
 '银色声浪': '1. Silver Waves',
 '灵动之流': '2. Vivid Flux',
 '和煦清风': '3. Serene Breeze',
 '声灵幻境': '4. Fractal Fusion',
 '纵声天地': '5. Granular Fuzz',
 '全新纯电GLB': 'GLB with EQ Technology',
 '全新GLB': 'GLB',
 '全新纯电GLA': 'GLA with EQ Technology',
 '全新GLA': 'GLA',
 '全新纯电长轴距C级车': 'C-Class L with EQ Technology',
 '全新纯电长轴距GLC SUV': 'GLC L with EQ Technology',
 '高速领航辅助驾驶': 'Highway NGA',
 '城区领航辅助驾驶': 'City NGA',
 '霁青': 'Dynastic Glaze',
 '玄黑': 'Enigma night',
 '栾华': 'Venerable goldrain tree',
 '月白': 'Lunar brilliance',
 '发光梅赛德斯-奔驰星标': 'Illuminated Mercedes star',
 '雾灰绿色 / 雾灰蓝色': 'aqua-mint non-metallic',
 '星徽之幕封闭式格栅': 'Panel with illuminated Mercedes-Benz pattern',
 '星流之翼贯穿式尾灯': 'Rear light strip',
 '星徽光漩': '尾灯',
 '星徽之瞳': '前灯',
 '全新纯电CLA': 'The Electric CLA',
 '全新纯电CLA 300 L': 'CLA 300 L',
 '全新纯电CLA 260 L': 'CLA 260 L',
 '纯电CLA 300 L 超长续航领智版': 'CLA 300 L Style',
 '纯电CLA 300 L 超长续航版': 'CLA 300 L Dynamic',
 '纯电 CLA 300 L 超长续航冠军版': "CLA 300 L Champion's Edition",
 '全数字仪表盘显示屏': 'Driver display',
 '前排乘客显示屏': 'MBUX Superscreen',
 '驾驶员无响应紧急停车': 'Emergency stop function with lane change',
 '侧面盲点辅助': 'Blind Spot Assist',
 '自动紧急制动': 'Brake Assist',
 '紧急转向辅助': 'Evasive steering function',
 '倒车影像': 'Reversing Camera',
 '侧面盲点辅助增强版': 'Blind Spot Assist Plus',
 '车道居中': 'Digital Extra: Steering Assist',
 '驻车定位系统': 'Digital Extra: PARKTRONIC',
 '智能泊车': 'Digital Extra: Parking Assist',
 '循迹倒车功能': 'Digital Extra: Reverse maneuvering function',
 '360°摄像头': 'Digital Extra: 360° camera',
 '车载娱乐应用': 'Pre-installation for MBUX Entertainment Advanced',
 '前备箱': 'Frunk',
 '面部识别': 'Facial recognition',
 '数字化产品和服务': 'Pre-installation for Digital Extras',
 '智能人机交互系统': 'MBUX Multimedia system premium++',
 '限速功能': 'Digital Extra: speed limit function',
 '直流充电系统': 'Direct current charging system',
 '车内乘员监测': 'Active rear passenger presence detection',
 '远程服务': 'Pre-installation for MB.CONNECT Package',
 '星迹相随贯穿式尾灯': 'Rear light strip',
 '星心相息封闭式格栅': 'Panel with illuminated Mercedes-Benz pattern',
 '素纹植纤维饰条': 'Matt white natural fiber silent lines trim elements',
 '水韵青': 'aquamarine blue metallic',
 'L2+': '导航辅助驾驶',
 'L2+ Highway Intelligent Assisted Driving': '高速领航辅助驾驶',
 'L2++ Urban & Highway Intelligent Assisted Driving': '城区及高速领航辅助驾驶',
 'R6强化学习大模型': 'R6 Reinforcement Learning Large Model',
 '温特图尔克海姆': 'Untertürkheim',
 '“人机共驾”': '‘Cooperative Steering’',
 '循迹倒车': 'Retrace Maneuver Assist (RMA)',
 '智能泊车 （全新一代）': 'Automatic Parking Assist (APA)',
 '记忆泊车': 'MVA',
 '油电同智': 'ICEs and NEVs sharing the same intelligence'}

MB_EN_TO_CN = {'Electric Drive Unit (EDU)': '电驱单元（EDU）',
 'two elastomer bearing levels': '两级弹性轴承',
 'double structure-borne noise': '双重隔音结构',
 '800-volt electric architecture': '800伏电气架构',
 'multi-source heat pump': '多源热泵系统',
 'Electric dual clutchless transmission (eDCT)': '电气化双离合变速箱（eDCT）',
 'SiC (Silicon Carbide) Inverter': '碳化硅逆变器',
 'Disconnect Unit (DCU)': '四驱断开装置 (DCU)',
 'OneBox braking system': 'OneBox制动系统',
 'two-speed gearbox / two-speed transmission': '两挡变速箱',
 '8F-eDCT': '电气化8速双离合变速箱',
 'Miller combustion process': '米勒循环',
 'NANOSLIDE® technology': 'NANOSLIDE®缸壁镀膜技术',
 'all-aluminium crankcase': '全铝合金曲轴箱',
 'start-stop function': '启停功能',
 'usable energy content': '可用容量',
 'energy content': '电池容量',
 'battery with lithium-iron phosphate cathodes (LFP)': '磷酸铁锂电池',
 'battery with lithium-ion technology': '锂离子电池',
 'Nickel-manganese-cobalt (NMC)': '镍钴锰三元锂电池',
 'battery SoC': '剩余电量百分比',
 'vehicle-to-home': '应急供电',
 'vehicle-to-grid': '向电网反向供电',
 'bidirectional DC wallbox': '双向直流充电墙盒',
 'flat-pack design': '扁平式设计',
 'liquid cooling system': '液冷系统',
 'PSM (Permanent Magnet Synchronous Machine)': '永磁同步电机',
 'winding of the stator': '定子绕组',
 'heavy rare earths': '重稀土',
 'D +': 'D+无能量回收模式',
 'D Auto': 'DAuto智能能量回收模式',
 'D standard recuperation': '标准能量回收',
 'D- increased recuperation': '加强能量回收',
 'ECO Assistant': '节能辅助系统（ECO Assist）',
 'Master cylinder': '制动泵',
 'Mercedes-Benz Operating System (MB.OS)': 'MB.OS全新架构',
 'Mercedes Benz Intelligent Cloud': '梅赛德斯-奔驰智能云',
 'MBUX Zero Layer': '零层级界面',
 'MBUX Superscreen': 'MBUX超级屏',
 'Mercedes-Benz User Experience (MBUX)': 'MBUX智能人机交互系统',
 'Mercedes-Benz Intelligent Cloud': '梅赛德斯-奔驰智能云',
 'MBUX Virtual Assistant': '奔驰虚拟助手',
 'MBUX Surround Navigation': '全新MBUX沉浸式导航',
 'Mercedes-Benz navigation with Electric Intelligence': 'EQ优化导航',
 'DISTRONIC adaptive cruise control': '自适应巡航ACC',
 'pole impact test': '柱碰测试',
 'multi-stage protection concept of the HV system': '多级高压安全理念',
 'full vehicle system test bench': '整车系统测试台（FVS）',
 'skateboard chassis': '滑板底盘',
 'Mercedes-Benz Modular Architecture (MMA)': '梅赛德斯-奔驰模块化架构（MMA）平台',
 'intelligent modularity': '智能模块化平台',
 'scalable skateboard design': '可扩展的滑板式设计',
 'Electric Software Hub (ESH)': '电动软件中心（ESH）',
 'Mercedes-Benz Technology Centre (MTC)': '梅赛德斯-奔驰技术中心（MTC）',
 'Mercedes-Benz Accident Research': '梅赛德斯-奔驰事故研究部门',
 'Ambition 2039': '2039愿景',
 'Ambition Letter': '“愿景承诺函”',
 'Electric Only': '全面电动',
 'Electric First': '电动为先',
 'Star Elite': '星睿品牌',
 'Private Charging': '星管家服务',
 'Public Charging': '星随行',
 'Brand Charging': '星驿站',
 'vision of zero traffic fatalities by 2050': '2050年零致命性交通事故愿景',
 '"Modern Luxury" product': '“新豪华主义”产品体验',
 '"Premium Customer Care"': '“心豪华主义”服务体验',
 'Sustainable Business Operation': '可持续的发展之道',
 'Sustainable Development of Local Society via CSR Commitment': '可持续的责任之道',
 'Sustainability in both business development and social responsibility': '商责并举',
 '“Sensual Purity” concept': '“感性·纯粹”理念',
 'DISTRONIC': '限距控制系统',
 'DISTRONIC PLUS': '限距控制系统增强版',
 'Active Distance Assist DISTRONIC': '智能领航限距功能',
 'BAS PLUS': '制动辅助系统增强版',
 'Active Lane Keeping Assist': '主动式车道保持辅助系统',
 'Adaptive Highbeam Assist Plus': '自适应远光灯辅助系统增强版',
 'Night View Assist Plus': '夜视辅助系统增强版',
 'COLLISION PREVENTION ASSIST PLUS': '碰撞预防辅助系统增强版',
 'ADAPTIVE BRAKE': '自适应制动',
 'Speed Limit Assist': '速度限制辅助系统',
 'Lane Keeping Assist': '车道保持辅助系统',
 'ATTENTION ASSIST': '注意力辅助系统',
 'PRE-SAFE®': '预防性安全系统',
 'DRIVE PILOT (200)': 'DRIVE PILOT驾驶领航系统',
 'Driving assistant package with DRIVE PILOT (P26)': 'DRIVE PILOT驾驶领航组件',
 'Automatic Lane Change （ALC）': '智能变道及导航辅助驾驶',
 'PRE-SAFE® Impulse Side.': '座椅侧碰保护功能',
 'adaptive cruise control': '自适应巡航控制系统',
 'NANOSLIDE® cylinder coating': 'NANOSLIDE®缸壁镀膜技术',
 'CONICSHAPE® cylinder honing': 'CONISHAPE®缸壁珩磨',
 'Permanently excited synchronous motor (PSM)': '永磁同步电机',
 'blanking function': '视角限制功能',
 'MBUX智能人机交互系统': 'MBUX',
 '"Hey Mercedes"': 'MBUX读心语音助理功能',
 'Magic Module': '读心感应助理',
 'ENERGIZING NATURE programs': '畅心醒神自然主题',
 'ENERGIZING COMFORT': '畅心醒神功能',
 'ENERGIZING AIR CONTROL Plus': '畅新空气护盾',
 'ENERGIZING AIR CONTROL': '雾霾终结者',
 'Comfort mode': '舒适模式',
 'Freshness': '舒展模式',
 'Warmth': '活力模式',
 'Vitality': '自在模式',
 'Joy': '恬淡模式',
 'Comfort': '悠然模式',
 'Training': '放松训练',
 'Assembly Shop': '总装车间',
 'Body Shop': '装焊车间',
 'Stamping Shop': '冲压车间',
 'Workshop Manager': '生产车间经理',
 'active rear-axle steering': '主动式后轮转向系统',
 'UI/UX': '用户界面/用户体验',
 'Active Brake Assist': '主动制动辅助系统',
 'World Premiere': '全球首秀',
 'Chinese Premiere': '中国首秀',
 'Continuous Damping Control': '减振器',
 'infotainment system': '人机交互',
 'Dyno Planning': '台架实验室的建设规划',
 'Final-Drive-Development': '卡车主减速器研发',
 'the sprint time from 0-100km/h of 3.4s': '3.4S的百公里加速时间',
 'energy recovery': '能量回收',
 'the three-pointed star': '三叉星徽',
 'Mercedes-Benz Advanced Design Center of China': '梅赛德斯-奔驰中国高级设计中心',
 'TCC（Tech Center China）': '梅赛德斯-奔驰中国研发技术中心',
 'Mercedes-Benz R&D Center Shanghai': '梅赛德斯-奔驰上海研发中心',
 'Sophisticated Luxury': '至臻豪华',
 'Performance Luxury': '性能豪华',
 'Progressive Luxury': '先锋豪华',
 'Adventurous Luxury': '拓界豪华',
 'Active Ambient Lighting': '主动式环境氛围灯',
 'AMG-specific radiator grille': 'AMG垂瀑式封闭格栅',
 'Affalterbach': '阿法特巴赫',
 'KLO-Knowledge Learning Officer': '未来研习官',
 'plug-in hybrid model': '插电式混合动力车型',
 'plug-in hybrid electric vehicle (PHEV)': '插电式混合动力车',
 'all-electric SUV': '纯电SUV',
 'off-road capability': '越野能力',
 'Mid-large SUV': '中大型SUV',
 'Large SUV': '大型SUV',
 '5-seater': '五座',
 'Over-the-Air': 'OTA远程升级',
 'Earth is our Pandora.': '地球，我们心中的潘多拉星球',
 'Every action counts. Join our journey to a fully electric future.': '每一步都有意义。一同启程，共赴电动未来。',
 'a safety body shell with a rigid passenger compartment and crumple zones at the front and rear': '带缓冲溃缩区与刚性乘员舱的安全车身',
 'to achieve accident-free driving by 2050': '到2050年实现“零致命性交通事故”',
 'Wind resistance': '风阻',
 'drag coefficient': '风阻系数',
 'DSR (Downhill Speed Regulation)': '陡坡缓降功能',
 'AMG’s "Affalterbach" emblem': 'AMG徽章',
 'AMG’s “Driving Performance"': 'AMG的“非凡驾驭”',
 'ACTIVE RIDE CONTROL': 'AMG主动行驶控制系统',
 'AMG RIDE CONTROL+ with air suspension, with adaptive controlled adjustable damping': '带自适应可调减振功能的AMG行驶控制增强版（AMG RIDE '
                                                                                       'CONTROL+）空气悬挂',
 'AMG DYNAMICS/ AMG Dynamics': 'AMG驾驶动态系统',
 'AMG Dynamics': '动感模式',
 'RACE START': '弹射起步',
 'AMG DYNAMICS dynamic control system': 'AMG驾驶动态控制系统',
 "AMG Driver's Package": 'AMG 驾驶套件',
 'Electronic Stability Program ESP®': '电控车辆稳定行驶系统（ESP®）',
 'rolling movement': '车身稳定性',
 'air diffuser': '空气扩散器',
 'front apron': '前裙板',
 'Wheel spoilers / rear spoiler': '扰流板',
 'side sill panel': '侧踏板',
 'AIR CURTAIN effect': '智能气帘效果',
 'Front splitter in high-gloss black with chrome trim and flics and fins on the air intakes. Air diffusers left and right in high-gloss black': '带镀铬饰边及高光黑色涂层的前分流器，进气口的翼片和风刀，以及左右两侧采用高光黑色涂层的空气扩散器',
 'AMG ceramic high-performance compound brake system': 'AMG陶瓷高性能复合制动系统',
 'AMG TRACK PACE': 'AMG TRACK PACE虚拟竞赛工程师',
 'AMG light-alloy wheels': 'AMG轻合金轮毂',
 'AMG Performance 4MATIC+ fully variable all-wheel drive': 'AMG高性能全时四轮驱动增强版',
 'graphite grey magno': '哑光石墨灰色',
 'Maybach emblem': '迈巴赫徽章/徽标',
 'Econyl': 'Econyl再生尼龙材料',
 'Top End Vehicle (TEV)': '高端车系',
 'BEV (Battery Electric Vehicle)': '纯电车型',
 'PHEV (Plug-in Hybrid Electric vehicle)': '插电式混合动力车型',
 'Driving Assistance package Plus': '驾驶辅助组件增强版',
 'digital vent control': '数字化风向调节',
 'trim & front light': '璀璨星河木饰板 & 璀璨星雨数字大灯',
 'Front illuminated grill': '璀璨星环格栅',
 'Rear light': '璀璨星芒尾灯',
 'Light carpet': '流星掠影光毯',
 'Backlit trim': '璀璨星河木饰板',
 'Circumferential ambient light': '360 ͦ环绕式环境氛围灯',
 'Sound visualisation': '随音悦动',
 'Front light': '璀璨星雨数字大灯',
 'Overall interior': '沉浸式智享座舱',
 'powerdome': '筋线',
 'Iconic Luxury': '经典先锋豪华',
 'Maybach Night Series': '极夜版本（Night Series）',
 'Defining Class since 1886': '定义时代风潮',
 'the world’s first automaker certified for Level 3 and Level 4 automated driving': '全球首家L3、L4“双持证”车企',
 'intelligent driving assistance': '智能驾驶系统',
 'Powertrain varies, Mercedes is always a Mercedes': '无论油电，都很奔驰',
 'Every luxury must have a story to pass on. Every luxury must be as sincerity as purity. Every luxury must last forever.': '“凡奢华美物，必有故事传承；凡奢华美物，必定表里如一；凡奢华美物，必将风格永存',
 'Carl Benz': '卡尔·奔驰',
 'RD in China for China and for the world': '中国研发 全球奔驰',
 'Growing in China, with China': '在华发展 与华共进',
 'developed in China, for China': '中国制造、专属中国',
 'Developed in China, innovating for the world': '以中国创新，领全球风潮',
 'China is our home away from home': '虽非故土，亲似家园',
 'A Mercedes-Benz must always look like a Mercedes-Benz.': '奔驰，一眼便知/ 一眼奔驰，风格始终',
 'driving assistance system': '智能驾驶辅助系统',
 'automated driving systems': '自动驾驶系统',
 'lounge concept': '“数字雅座”',
 'navigation with Electric Intelligence ->Mercedes-Benz Navigation with Electric Intelligence': 'EQ优化导航 改为 '
                                                                                                '梅赛德斯-奔驰电动智能导航',
 'Mercedes-Benz branded high-power charging stations': '梅赛德斯-奔驰超级充电站',
 'e-Drive system': '三电系统',
 'heat pump': '热泵系统',
 'Standards of Mercedes-Benz': '奔驰的标准',
 'MBUX SOUND DRIVE': '随行乐动',
 'Magic Body Control': '智能车身控制（Magic Body Control）',
 'E-ACTIVE BODY CONTROL': '智能魔术车身控制系统（E-ACTIVE BODY CONTROL）',
 'EN': 'CN',
 'W463 G-Class': '纯电G级越野车 (7words, and “纯电” reflect “EQ Technology” properly)',
 'G 350': '纯电G 580 (Ml Nov 2024)',
 'G 500': '纯电G 580 先型特别版 (Ml July 2024)',
 'AMG.EA': 'AMG.EA纯电架构平台',
 'AMG Real Performance Sound': 'AMG高性能音浪',
 'G-ROAR': 'G-ROAR 专属声浪',
 'Low range': '低速越野 （based on function）',
 'Offroad crawling': '越野爬行 (based on function)',
 'Torque vectoring': '扭矩矢量分配 (based on function)',
 'Offroad Track': '越野赛道 (based on function)',
 'Design box': '车尾装饰盒 (取代后边备胎轮毂罩，原本是放charging cable的，不过我们也不提供cable，其实就是一个塑料的小书包)',
 'MANUFAKTUR southsea blue magno': 'MANUFAKTUR哑光澄海蓝色',
 'Illuminated Mercedes star': '发光星标',
 'Panel with illuminated Mercedes-Benz pattern': '叠影星空/ 流光星徽 / 璀璨星河 封闭式格栅',
 'aqua-mint non-metallic': '雾灰绿色',
 'Clear blue': '晴空蓝色',
 'Panoramic roof': '全景式天幕',
 'Rear light strip': '星辰轨迹 / 矩阵星轨 /星驰光轨 / 璀璨星轨 贯穿式尾灯',
 'tech grey': '冷空灰',
 'Driver display': 'MBUX.超感屏 / MBUX.超级屏',
 "Ship's deck open-pore brown oak trim elements with aluminium lines": '嵌铝质饰条的棕色开孔型橡木饰条',
 'Open-pore grey birch wood trim elements': '灰色开孔型桦木木饰条',
 'Matt white natural fibre silent lines trim elements': '哑光白色暗纹天然纤维饰条',
 'Digital Extra: MB.DRIVE ASSIST': 'MB.Drive辅助驾驶',
 'Digital Extra: MB.DRIVE ASSIST PRO': 'MB.Drive辅助驾驶Pro',
 'Digital Extra: MBUX Navigation': '沉浸式导航',
 'Mercedes-Benz Navigation with Electric Intelligence': '梅赛德斯-奔驰电动智能导航',
 'Digital Extra: GUARD 360° vehicle protection plus': '驻车守护',
 '1. Silver Waves': '银色声浪',
 '2. Vivid Flux': '灵动之流',
 '3. Serene Breeze': '和煦清风',
 '4. Fractal Fusion': '声灵幻境',
 '5. Granular Fuzz': '纵声天地',
 'GLB with EQ Technology': '全新纯电GLB',
 'GLB': '全新GLB',
 'GLA with EQ Technology': '全新纯电GLA',
 'GLA': '全新GLA',
 'C-Class L with EQ Technology': '全新纯电长轴距C级车',
 'GLC L with EQ Technology': '全新纯电长轴距GLC SUV',
 'Highway NGA': '高速领航辅助驾驶',
 'City NGA': '城区领航辅助驾驶',
 'Dynastic Glaze': '霁青',
 'Enigma night': '玄黑',
 'Venerable goldrain tree': '栾华',
 'Lunar brilliance': '月白',
 "Ship's deck open-pore brown oak trim elements with aluminum lines": '嵌铝质饰条的棕色开孔型橡木饰条',
 'Matt white natural fiber silent lines trim elements': '哑光白色暗纹天然纤维饰条',
 '尾灯': '星徽光漩',
 '前灯': '星徽之瞳',
 'The Electric CLA': '全新纯电CLA',
 'CLA 300 L': '全新纯电CLA 300 L',
 'CLA 260 L': '全新纯电CLA 260 L',
 'CLA 300 L Style': '纯电CLA 300 L 超长续航领智版',
 'CLA 300 L Dynamic': '纯电CLA 300 L 超长续航版',
 "CLA 300 L Champion's Edition": '纯电 CLA 300 L 超长续航冠军版',
 'Emergency stop function with lane change': '驾驶员无响应紧急停车',
 'Blind Spot Assist': '侧面盲点辅助',
 'Brake Assist': '自动紧急制动',
 'Evasive steering function': '紧急转向辅助',
 'Reversing Camera': '倒车影像',
 'Blind Spot Assist Plus': '侧面盲点辅助增强版',
 'Digital Extra: Steering Assist': '车道居中',
 'Digital Extra: PARKTRONIC': '驻车定位系统',
 'Digital Extra: Parking Assist': '智能泊车',
 'Digital Extra: Reverse maneuvering function': '循迹倒车功能',
 'Digital Extra: 360° camera': '360°摄像头',
 'Pre-installation for MBUX Entertainment Advanced': '车载娱乐应用',
 'Frunk': '前备箱',
 'Facial recognition': '面部识别',
 'Pre-installation for Digital Extras': '数字化产品和服务',
 'MBUX Multimedia system premium++': '智能人机交互系统',
 'Digital Extra: speed limit function': '限速功能',
 'Direct current charging system': '直流充电系统',
 'Active rear passenger presence detection': '车内乘员监测',
 'Pre-installation for MB.CONNECT Package': '远程服务',
 '前车灯': '星徽之瞳',
 '后车灯': '星徽光漩',
 'aquamarine blue metallic': '水韵青',
 '导航辅助驾驶': 'L2+',
 '高速领航辅助驾驶': 'L2+ Highway Intelligent Assisted Driving',
 '城区及高速领航辅助驾驶': 'L2++ Urban & Highway Intelligent Assisted Driving',
 'R6 Reinforcement Learning Large Model': 'R6强化学习大模型',
 'Untertürkheim': '温特图尔克海姆',
 '‘Cooperative Steering’': '“人机共驾”',
 'Retrace Maneuver Assist (RMA)': '循迹倒车',
 'Automatic Parking Assist (APA)': '智能泊车 （全新一代）',
 'MVA': '记忆泊车',
 'ICEs and NEVs sharing the same intelligence': '油电同智'}

# Structured term entries with optional category/note
MB_TERM_ENTRIES = [{'category': '驱动', 'cn': '电驱单元（EDU）', 'en': 'Electric Drive Unit (EDU)'},
 {'category': None, 'cn': '两级弹性轴承', 'en': 'two elastomer bearing levels'},
 {'category': None, 'cn': '双重隔音结构', 'en': 'double structure-borne noise'},
 {'category': None, 'cn': '800伏电气架构', 'en': '800-volt electric architecture'},
 {'category': None, 'cn': '多源热泵系统', 'en': 'multi-source heat pump'},
 {'category': None, 'cn': '电气化双离合变速箱（eDCT）', 'en': 'Electric dual clutchless transmission (eDCT)'},
 {'category': None, 'cn': '碳化硅逆变器', 'en': 'SiC (Silicon Carbide) Inverter'},
 {'category': None, 'cn': '四驱断开装置 (DCU)', 'en': 'Disconnect Unit (DCU)'},
 {'category': None, 'cn': 'OneBox制动系统', 'en': 'OneBox braking system'},
 {'category': None, 'cn': '两挡变速箱', 'en': 'two-speed gearbox / two-speed transmission'},
 {'category': None, 'cn': '电气化8速双离合变速箱', 'en': '8F-eDCT'},
 {'category': None, 'cn': '米勒循环', 'en': 'Miller combustion process'},
 {'category': None, 'cn': 'NANOSLIDE®缸壁镀膜技术', 'en': 'NANOSLIDE® technology'},
 {'category': None, 'cn': '全铝合金曲轴箱', 'en': 'all-aluminium crankcase'},
 {'category': None, 'cn': '启停功能', 'en': 'start-stop function'},
 {'category': '电池', 'cn': '可用容量', 'en': 'usable energy content'},
 {'category': None, 'cn': '电池容量', 'en': 'energy content'},
 {'category': None, 'cn': '磷酸铁锂电池', 'en': 'battery with lithium-iron phosphate cathodes (LFP)'},
 {'category': None, 'cn': '锂离子电池', 'en': 'battery with lithium-ion technology'},
 {'category': None, 'cn': '镍钴锰三元锂电池', 'en': 'Nickel-manganese-cobalt (NMC)'},
 {'category': None, 'cn': '剩余电量百分比', 'en': 'battery SoC'},
 {'category': None, 'cn': '应急供电', 'en': 'vehicle-to-home'},
 {'category': None, 'cn': '向电网反向供电', 'en': 'vehicle-to-grid'},
 {'category': None, 'cn': '双向直流充电墙盒', 'en': 'bidirectional DC wallbox'},
 {'category': None, 'cn': '扁平式设计', 'en': 'flat-pack design'},
 {'category': None, 'cn': '液冷系统', 'en': 'liquid cooling system'},
 {'category': '电机', 'cn': '永磁同步电机', 'en': 'PSM (Permanent Magnet Synchronous Machine)'},
 {'category': None, 'cn': '定子绕组', 'en': 'winding of the stator'},
 {'category': None, 'cn': '重稀土', 'en': 'heavy rare earths'},
 {'category': '能量回收', 'cn': 'D+无能量回收模式', 'en': 'D +'},
 {'category': None, 'cn': 'DAuto智能能量回收模式', 'en': 'D Auto'},
 {'category': None, 'cn': '标准能量回收', 'en': 'D standard recuperation'},
 {'category': None, 'cn': '加强能量回收', 'en': 'D- increased recuperation'},
 {'category': None, 'cn': '节能辅助系统（ECO Assist）', 'en': 'ECO Assistant'},
 {'category': '制动', 'cn': '制动泵', 'en': 'Master cylinder'},
 {'category': '智能', 'cn': 'MB.OS全新架构', 'en': 'Mercedes-Benz Operating System (MB.OS)'},
 {'category': None, 'cn': '梅赛德斯-奔驰智能云', 'en': 'Mercedes Benz Intelligent Cloud'},
 {'category': '智舱', 'cn': '零层级界面', 'en': 'MBUX Zero Layer'},
 {'category': None, 'cn': 'MBUX超级屏', 'en': 'MBUX Superscreen'},
 {'category': None, 'cn': 'MBUX智能人机交互系统', 'en': 'Mercedes-Benz User Experience (MBUX)'},
 {'category': None, 'cn': '梅赛德斯-奔驰智能云', 'en': 'Mercedes-Benz Intelligent Cloud'},
 {'category': None, 'cn': '奔驰虚拟助手', 'en': 'MBUX Virtual Assistant'},
 {'category': None, 'cn': '全新MBUX沉浸式导航', 'en': 'MBUX Surround Navigation'},
 {'category': '智驾', 'cn': 'EQ优化导航', 'en': 'Mercedes-Benz navigation with Electric Intelligence'},
 {'category': None, 'cn': '自适应巡航ACC', 'en': 'DISTRONIC adaptive cruise control'},
 {'category': '安全', 'cn': '柱碰测试', 'en': 'pole impact test'},
 {'category': None, 'cn': '多级高压安全理念', 'en': 'multi-stage protection concept of the HV system'},
 {'category': '测试', 'cn': '整车系统测试台（FVS）', 'en': 'full vehicle system test bench'},
 {'category': '底盘', 'cn': '滑板底盘', 'en': 'skateboard chassis'},
 {'category': '平台', 'cn': '梅赛德斯-奔驰模块化架构（MMA）平台', 'en': 'Mercedes-Benz Modular Architecture (MMA)'},
 {'category': None, 'cn': '智能模块化平台', 'en': 'intelligent modularity'},
 {'category': None, 'cn': '可扩展的滑板式设计', 'en': 'scalable skateboard design'},
 {'category': '部门/地点', 'cn': '电动软件中心（ESH）', 'en': 'Electric Software Hub (ESH)'},
 {'category': None, 'cn': '梅赛德斯-奔驰技术中心（MTC）', 'en': 'Mercedes-Benz Technology Centre (MTC)'},
 {'category': None, 'cn': '梅赛德斯-奔驰事故研究部门', 'en': 'Mercedes-Benz Accident Research'},
 {'category': 'Words', 'cn': '2039愿景', 'en': 'Ambition 2039', 'note': None},
 {'category': 'Words',
  'cn': '“愿景承诺函”',
  'en': 'Ambition Letter',
  'note': 'https://mp.weixin.qq.com/s/zVk_9qUajRJVkk8JOxE3hw'},
 {'category': 'Words', 'cn': '全面电动', 'en': 'Electric Only', 'note': None},
 {'category': 'Words', 'cn': '电动为先', 'en': 'Electric First', 'note': None},
 {'category': 'Words', 'cn': '星睿品牌', 'en': 'Star Elite', 'note': None},
 {'category': 'Words', 'cn': '星管家服务', 'en': 'Private Charging', 'note': None},
 {'category': 'Words', 'cn': '星随行', 'en': 'Public Charging', 'note': None},
 {'category': 'Words', 'cn': '星驿站', 'en': 'Brand Charging', 'note': None},
 {'category': 'Words', 'cn': '2050年零致命性交通事故愿景', 'en': 'vision of zero traffic fatalities by 2050', 'note': None},
 {'category': 'Words', 'cn': '“新豪华主义”产品体验', 'en': '"Modern Luxury" product', 'note': None},
 {'category': 'Words', 'cn': '“心豪华主义”服务体验', 'en': '"Premium Customer Care"', 'note': None},
 {'category': 'Words', 'cn': '可持续的发展之道', 'en': 'Sustainable Business Operation', 'note': None},
 {'category': 'Words',
  'cn': '可持续的责任之道',
  'en': 'Sustainable Development of Local Society via CSR Commitment',
  'note': None},
 {'category': 'Words',
  'cn': '商责并举',
  'en': 'Sustainability in both business development and social responsibility',
  'note': None},
 {'category': 'Words', 'cn': '“感性·纯粹”理念', 'en': '“Sensual Purity” concept', 'note': None},
 {'category': 'Words', 'cn': '限距控制系统', 'en': 'DISTRONIC', 'note': None},
 {'category': 'Words', 'cn': '限距控制系统增强版', 'en': 'DISTRONIC PLUS', 'note': None},
 {'category': 'Words', 'cn': '智能领航限距功能', 'en': 'Active Distance Assist DISTRONIC', 'note': None},
 {'category': 'Words', 'cn': '制动辅助系统增强版', 'en': 'BAS PLUS', 'note': None},
 {'category': 'Words', 'cn': '主动式车道保持辅助系统', 'en': 'Active Lane Keeping Assist', 'note': None},
 {'category': 'Words', 'cn': '自适应远光灯辅助系统增强版', 'en': 'Adaptive Highbeam Assist Plus', 'note': None},
 {'category': 'Words', 'cn': '夜视辅助系统增强版', 'en': 'Night View Assist Plus', 'note': None},
 {'category': 'Words', 'cn': '碰撞预防辅助系统增强版', 'en': 'COLLISION PREVENTION ASSIST PLUS', 'note': None},
 {'category': 'Words', 'cn': '自适应制动', 'en': 'ADAPTIVE BRAKE', 'note': None},
 {'category': 'Words', 'cn': '速度限制辅助系统', 'en': 'Speed Limit Assist', 'note': None},
 {'category': 'Words', 'cn': '车道保持辅助系统', 'en': 'Lane Keeping Assist', 'note': None},
 {'category': 'Words', 'cn': '注意力辅助系统', 'en': 'ATTENTION ASSIST', 'note': None},
 {'category': 'Words', 'cn': '预防性安全系统', 'en': 'PRE-SAFE®', 'note': None},
 {'category': 'Words', 'cn': 'DRIVE PILOT驾驶领航系统', 'en': 'DRIVE PILOT (200)', 'note': None},
 {'category': 'Words',
  'cn': 'DRIVE PILOT驾驶领航组件',
  'en': 'Driving assistant package with DRIVE PILOT (P26)',
  'note': None},
 {'category': 'Words', 'cn': '智能变道及导航辅助驾驶', 'en': 'Automatic Lane Change （ALC）', 'note': None},
 {'category': 'Words', 'cn': '座椅侧碰保护功能', 'en': 'PRE-SAFE® Impulse Side.', 'note': None},
 {'category': 'Words', 'cn': '自适应巡航控制系统', 'en': 'adaptive cruise control', 'note': None},
 {'category': 'Words', 'cn': 'NANOSLIDE®缸壁镀膜技术', 'en': 'NANOSLIDE® cylinder coating', 'note': None},
 {'category': 'Words', 'cn': 'CONISHAPE®缸壁珩磨', 'en': 'CONICSHAPE® cylinder honing', 'note': None},
 {'category': 'Words',
  'cn': '永磁同步电机',
  'en': 'Permanently excited synchronous motor (PSM)',
  'note': 'permanently excited synchronous motors'},
 {'category': 'Words', 'cn': '视角限制功能', 'en': 'blanking function', 'note': None},
 {'category': 'Words',
  'cn': 'MBUX',
  'en': 'MBUX智能人机交互系统',
  'note': 'Mercedes-Benz User Experience infotainment system that can be controlled via voice and touch input'},
 {'category': 'Words', 'cn': 'MBUX读心语音助理功能', 'en': '"Hey Mercedes"', 'note': None},
 {'category': 'Words', 'cn': '读心感应助理', 'en': 'Magic Module', 'note': None},
 {'category': 'Words', 'cn': '畅心醒神自然主题', 'en': 'ENERGIZING NATURE programs', 'note': None},
 {'category': 'Words', 'cn': '畅心醒神功能', 'en': 'ENERGIZING COMFORT', 'note': None},
 {'category': 'Words', 'cn': '畅新空气护盾', 'en': 'ENERGIZING AIR CONTROL Plus', 'note': None},
 {'category': 'Words', 'cn': '雾霾终结者', 'en': 'ENERGIZING AIR CONTROL', 'note': None},
 {'category': 'Words', 'cn': '舒适模式', 'en': 'Comfort mode', 'note': None},
 {'category': 'Words', 'cn': '舒展模式', 'en': 'Freshness', 'note': None},
 {'category': 'Words', 'cn': '活力模式', 'en': 'Warmth', 'note': None},
 {'category': 'Words', 'cn': '自在模式', 'en': 'Vitality', 'note': None},
 {'category': 'Words', 'cn': '恬淡模式', 'en': 'Joy', 'note': None},
 {'category': 'Words', 'cn': '悠然模式', 'en': 'Comfort', 'note': None},
 {'category': 'Words', 'cn': '放松训练', 'en': 'Training', 'note': None},
 {'category': 'Words', 'cn': '总装车间', 'en': 'Assembly Shop', 'note': None},
 {'category': 'Words', 'cn': '装焊车间', 'en': 'Body Shop', 'note': None},
 {'category': 'Words', 'cn': '冲压车间', 'en': 'Stamping Shop', 'note': None},
 {'category': 'Words', 'cn': '生产车间经理', 'en': 'Workshop Manager', 'note': None},
 {'category': 'Words', 'cn': '主动式后轮转向系统', 'en': 'active rear-axle steering', 'note': None},
 {'category': 'Words', 'cn': '用户界面/用户体验', 'en': 'UI/UX', 'note': None},
 {'category': 'Words', 'cn': '主动制动辅助系统', 'en': 'Active Brake Assist', 'note': None},
 {'category': 'Words', 'cn': '主动车道保持辅助系统', 'en': 'Active Lane Keeping Assist', 'note': None},
 {'category': 'Words', 'cn': '全球首秀', 'en': 'World Premiere', 'note': None},
 {'category': 'Words', 'cn': '中国首秀', 'en': 'Chinese Premiere', 'note': None},
 {'category': 'Words', 'cn': '减振器', 'en': 'Continuous Damping Control', 'note': None},
 {'category': 'Words', 'cn': '人机交互', 'en': 'infotainment system', 'note': None},
 {'category': 'Words', 'cn': '台架实验室的建设规划', 'en': 'Dyno Planning', 'note': None},
 {'category': 'Words', 'cn': '卡车主减速器研发', 'en': 'Final-Drive-Development', 'note': None},
 {'category': 'Words', 'cn': '3.4S的百公里加速时间', 'en': 'the sprint time from 0-100km/h of 3.4s', 'note': None},
 {'category': 'Words', 'cn': '能量回收', 'en': 'energy recovery', 'note': None},
 {'category': 'Words', 'cn': '三叉星徽', 'en': 'the three-pointed star', 'note': None},
 {'category': 'Words', 'cn': '梅赛德斯-奔驰中国高级设计中心', 'en': 'Mercedes-Benz Advanced Design Center of China', 'note': None},
 {'category': 'Words', 'cn': '梅赛德斯-奔驰中国研发技术中心', 'en': 'TCC（Tech Center China）', 'note': None},
 {'category': 'Words', 'cn': '梅赛德斯-奔驰上海研发中心', 'en': 'Mercedes-Benz R&D Center Shanghai', 'note': None},
 {'category': 'Words', 'cn': '至臻豪华', 'en': 'Sophisticated Luxury', 'note': None},
 {'category': 'Words', 'cn': '性能豪华', 'en': 'Performance Luxury', 'note': None},
 {'category': 'Words', 'cn': '先锋豪华', 'en': 'Progressive Luxury', 'note': None},
 {'category': 'Words', 'cn': '拓界豪华', 'en': 'Adventurous Luxury', 'note': None},
 {'category': 'Words', 'cn': '主动式环境氛围灯', 'en': 'Active Ambient Lighting', 'note': None},
 {'category': 'Words', 'cn': 'AMG垂瀑式封闭格栅', 'en': 'AMG-specific radiator grille', 'note': None},
 {'category': 'Words', 'cn': '阿法特巴赫', 'en': 'Affalterbach', 'note': None},
 {'category': 'Words', 'cn': '未来研习官', 'en': 'KLO-Knowledge Learning Officer', 'note': None},
 {'category': 'Words', 'cn': '插电式混合动力车型', 'en': 'plug-in hybrid model', 'note': None},
 {'category': 'Words', 'cn': '插电式混合动力车', 'en': 'plug-in hybrid electric vehicle (PHEV)', 'note': None},
 {'category': 'Words', 'cn': '纯电SUV', 'en': 'all-electric SUV', 'note': None},
 {'category': 'Words', 'cn': '越野能力', 'en': 'off-road capability', 'note': None},
 {'category': 'Words', 'cn': '中大型SUV', 'en': 'Mid-large SUV', 'note': None},
 {'category': 'Words', 'cn': '大型SUV', 'en': 'Large SUV', 'note': None},
 {'category': 'Words', 'cn': '五座', 'en': '5-seater', 'note': None},
 {'category': 'Words', 'cn': 'OTA远程升级', 'en': 'Over-the-Air', 'note': None},
 {'category': 'Words', 'cn': '地球，我们心中的潘多拉星球', 'en': 'Earth is our Pandora.', 'note': None},
 {'category': 'Words',
  'cn': '每一步都有意义。一同启程，共赴电动未来。',
  'en': 'Every action counts. Join our journey to a fully electric future.',
  'note': None},
 {'category': 'Words',
  'cn': '带缓冲溃缩区与刚性乘员舱的安全车身',
  'en': 'a safety body shell with a rigid passenger compartment and crumple zones at the front and rear',
  'note': None},
 {'category': 'Words', 'cn': '到2050年实现“零致命性交通事故”', 'en': 'to achieve accident-free driving by 2050', 'note': None},
 {'category': 'Words', 'cn': '风阻', 'en': 'Wind resistance', 'note': None},
 {'category': 'Words', 'cn': '风阻系数', 'en': 'drag coefficient', 'note': None},
 {'category': 'Words', 'cn': '陡坡缓降功能', 'en': 'DSR (Downhill Speed Regulation)', 'note': None},
 {'category': 'Words', 'cn': 'AMG徽章', 'en': 'AMG’s "Affalterbach" emblem', 'note': None},
 {'category': 'Words', 'cn': 'AMG的“非凡驾驭”', 'en': 'AMG’s “Driving Performance"', 'note': None},
 {'category': 'Words', 'cn': 'AMG主动行驶控制系统', 'en': 'ACTIVE RIDE CONTROL', 'note': None},
 {'category': 'Words',
  'cn': '带自适应可调减振功能的AMG行驶控制增强版（AMG RIDE CONTROL+）空气悬挂',
  'en': 'AMG RIDE CONTROL+ with air suspension, with adaptive controlled adjustable damping',
  'note': None},
 {'category': 'Words', 'cn': 'AMG驾驶动态系统', 'en': 'AMG DYNAMICS/ AMG Dynamics', 'note': None},
 {'category': 'Words', 'cn': '动感模式', 'en': 'AMG Dynamics', 'note': None},
 {'category': 'Words', 'cn': '弹射起步', 'en': 'RACE START', 'note': None},
 {'category': 'Words', 'cn': 'AMG驾驶动态控制系统', 'en': 'AMG DYNAMICS dynamic control system', 'note': None},
 {'category': 'Words', 'cn': 'AMG 驾驶套件', 'en': "AMG Driver's Package", 'note': None},
 {'category': 'Words', 'cn': '电控车辆稳定行驶系统（ESP®）', 'en': 'Electronic Stability Program ESP®', 'note': None},
 {'category': 'Words', 'cn': '车身稳定性', 'en': 'rolling movement', 'note': None},
 {'category': 'Words', 'cn': '空气扩散器', 'en': 'air diffuser', 'note': None},
 {'category': 'Words', 'cn': '前裙板', 'en': 'front apron', 'note': None},
 {'category': 'Words', 'cn': '扰流板', 'en': 'Wheel spoilers / rear spoiler', 'note': None},
 {'category': 'Words', 'cn': '侧踏板', 'en': 'side sill panel', 'note': None},
 {'category': 'Words', 'cn': '智能气帘效果', 'en': 'AIR CURTAIN effect', 'note': None},
 {'category': 'Words',
  'cn': '带镀铬饰边及高光黑色涂层的前分流器，进气口的翼片和风刀，以及左右两侧采用高光黑色涂层的空气扩散器',
  'en': 'Front splitter in high-gloss black with chrome trim and flics and fins on the air intakes. Air diffusers left '
        'and right in high-gloss black',
  'note': None},
 {'category': 'Words',
  'cn': 'AMG陶瓷高性能复合制动系统',
  'en': 'AMG ceramic high-performance compound brake system',
  'note': None},
 {'category': 'Words', 'cn': 'AMG TRACK PACE虚拟竞赛工程师', 'en': 'AMG TRACK PACE', 'note': None},
 {'category': 'Words', 'cn': 'AMG轻合金轮毂', 'en': 'AMG light-alloy wheels', 'note': None},
 {'category': 'Words',
  'cn': 'AMG高性能全时四轮驱动增强版',
  'en': 'AMG Performance 4MATIC+ fully variable all-wheel drive',
  'note': None},
 {'category': 'Words', 'cn': '哑光石墨灰色', 'en': 'graphite grey magno', 'note': None},
 {'category': 'Words', 'cn': '迈巴赫徽章/徽标', 'en': 'Maybach emblem', 'note': None},
 {'category': 'Words', 'cn': 'Econyl再生尼龙材料', 'en': 'Econyl', 'note': '迈巴赫Night Series翻译'},
 {'category': 'Words', 'cn': '高端车系', 'en': 'Top End Vehicle (TEV)', 'note': None},
 {'category': 'Words', 'cn': '纯电车型', 'en': 'BEV (Battery Electric Vehicle)', 'note': None},
 {'category': 'Words', 'cn': '插电式混合动力车型', 'en': 'PHEV (Plug-in Hybrid Electric vehicle)', 'note': None},
 {'category': 'Words', 'cn': '驾驶辅助组件增强版', 'en': 'Driving Assistance package Plus', 'note': None},
 {'category': 'Words', 'cn': '数字化风向调节', 'en': 'digital vent control', 'note': None},
 {'category': 'Words', 'cn': '璀璨星河木饰板 & 璀璨星雨数字大灯', 'en': 'trim & front light', 'note': '待确认'},
 {'category': 'Words', 'cn': '璀璨星环格栅', 'en': 'Front illuminated grill', 'note': None},
 {'category': 'Words', 'cn': '璀璨星芒尾灯', 'en': 'Rear light', 'note': None},
 {'category': 'Words', 'cn': '流星掠影光毯', 'en': 'Light carpet', 'note': None},
 {'category': 'Words', 'cn': '璀璨星河木饰板', 'en': 'Backlit trim', 'note': None},
 {'category': 'Words', 'cn': '360 ͦ环绕式环境氛围灯', 'en': 'Circumferential ambient light', 'note': None},
 {'category': 'Words', 'cn': '随音悦动', 'en': 'Sound visualisation', 'note': None},
 {'category': 'Words', 'cn': '璀璨星雨数字大灯', 'en': 'Front light', 'note': None},
 {'category': 'Words', 'cn': '沉浸式智享座舱', 'en': 'Overall interior', 'note': None},
 {'category': 'Words', 'cn': '筋线', 'en': 'powerdome', 'note': None},
 {'category': 'Words', 'cn': '经典先锋豪华', 'en': 'Iconic Luxury', 'note': None},
 {'category': 'Words', 'cn': '极夜版本（Night Series）', 'en': 'Maybach Night Series', 'note': None},
 {'category': 'Words', 'cn': '定义时代风潮', 'en': 'Defining Class since 1886', 'note': None},
 {'category': 'Words',
  'cn': '全球首家L3、L4“双持证”车企',
  'en': 'the world’s first automaker certified for Level 3 and Level 4 automated driving',
  'note': None},
 {'category': 'Words', 'cn': '智能驾驶系统', 'en': 'intelligent driving assistance', 'note': None},
 {'category': 'Words', 'cn': '无论油电，都很奔驰', 'en': 'Powertrain varies, Mercedes is always a Mercedes', 'note': None},
 {'category': 'Words',
  'cn': '“凡奢华美物，必有故事传承；凡奢华美物，必定表里如一；凡奢华美物，必将风格永存',
  'en': 'Every luxury must have a story to pass on. Every luxury must be as sincerity as purity. Every luxury must '
        'last forever.',
  'note': None},
 {'category': 'Words', 'cn': '卡尔·奔驰', 'en': 'Carl Benz', 'note': 'the invention of the automobile by Carl Benz'},
 {'category': 'Words', 'cn': '中国研发 全球奔驰', 'en': 'RD in China for China and for the world', 'note': None},
 {'category': 'Words', 'cn': '在华发展 与华共进', 'en': 'Growing in China, with China', 'note': None},
 {'category': 'Words', 'cn': '中国制造、专属中国', 'en': 'developed in China, for China', 'note': None},
 {'category': 'Words', 'cn': '以中国创新，领全球风潮', 'en': 'Developed in China, innovating for the world', 'note': None},
 {'category': 'Words', 'cn': '虽非故土，亲似家园', 'en': 'China is our home away from home', 'note': None},
 {'category': 'Words',
  'cn': '奔驰，一眼便知/ 一眼奔驰，风格始终',
  'en': 'A Mercedes-Benz must always look like a Mercedes-Benz.',
  'note': None},
 {'category': 'Words', 'cn': '智能驾驶辅助系统', 'en': 'driving assistance system', 'note': None},
 {'category': 'Words', 'cn': '自动驾驶系统', 'en': 'automated driving systems', 'note': None},
 {'category': 'Words', 'cn': '“数字雅座”', 'en': 'lounge concept', 'note': 'CLE/v111'},
 {'category': 'Words',
  'cn': 'EQ优化导航 改为 梅赛德斯-奔驰电动智能导航',
  'en': 'navigation with Electric Intelligence ->Mercedes-Benz Navigation with Electric Intelligence',
  'note': None},
 {'category': 'Words', 'cn': '梅赛德斯-奔驰超级充电站', 'en': 'Mercedes-Benz branded high-power charging stations', 'note': None},
 {'category': 'Words', 'cn': '三电系统', 'en': 'e-Drive system', 'note': None},
 {'category': 'Words', 'cn': '热泵系统', 'en': 'heat pump', 'note': None},
 {'category': 'Words', 'cn': '奔驰的标准', 'en': 'Standards of Mercedes-Benz', 'note': None},
 {'category': 'Words', 'cn': '随行乐动', 'en': 'MBUX SOUND DRIVE', 'note': None},
 {'category': 'Words', 'cn': '智能车身控制（Magic Body Control）', 'en': 'Magic Body Control', 'note': None},
 {'category': 'Words', 'cn': '智能魔术车身控制系统（E-ACTIVE BODY CONTROL）', 'en': 'E-ACTIVE BODY CONTROL', 'note': None},
 {'category': 'Words', 'cn': 'CN', 'en': 'EN', 'note': 'CN'},
 {'category': 'Words',
  'cn': '纯电G级越野车 (7words, and “纯电” reflect “EQ Technology” properly)',
  'en': 'W463 G-Class',
  'note': 'G级越野车'},
 {'category': 'Words', 'cn': '纯电G 580 (Ml Nov 2024)', 'en': 'G 350', 'note': 'G 350'},
 {'category': 'Words', 'cn': '纯电G 580 先型特别版 (Ml July 2024)', 'en': 'G 500', 'note': 'G 500'},
 {'category': 'Words', 'cn': 'AMG.EA纯电架构平台', 'en': 'AMG.EA', 'note': None},
 {'category': 'Words', 'cn': 'AMG高性能音浪', 'en': 'AMG Real Performance Sound', 'note': None},
 {'category': 'Words', 'cn': 'G-ROAR 专属声浪', 'en': 'G-ROAR', 'note': '6V0'},
 {'category': 'Words', 'cn': '低速越野 （based on function）', 'en': 'Low range', 'note': '01Q'},
 {'category': 'Words', 'cn': '越野爬行 (based on function)', 'en': 'Offroad crawling', 'note': '05Q'},
 {'category': 'Words', 'cn': '扭矩矢量分配 (based on function)', 'en': 'Torque vectoring', 'note': 'A60'},
 {'category': 'Words', 'cn': '越野赛道 (based on function)', 'en': 'Offroad Track', 'note': '0K1'},
 {'category': 'Words',
  'cn': '车尾装饰盒 (取代后边备胎轮毂罩，原本是放charging cable的，不过我们也不提供cable，其实就是一个塑料的小书包)',
  'en': 'Design box',
  'note': 'RS2'},
 {'category': 'Words', 'cn': 'MANUFAKTUR哑光澄海蓝色', 'en': 'MANUFAKTUR southsea blue magno', 'note': '591U'},
 {'category': 'Words', 'cn': '发光星标', 'en': 'Illuminated Mercedes star', 'note': '24U'},
 {'category': 'Words',
  'cn': '叠影星空/ 流光星徽 / 璀璨星河 封闭式格栅',
  'en': 'Panel with illuminated Mercedes-Benz pattern',
  'note': '4B7'},
 {'category': 'Words', 'cn': '雾灰绿色', 'en': 'aqua-mint non-metallic', 'note': '341U'},
 {'category': 'Words', 'cn': '晴空蓝色', 'en': 'Clear blue', 'note': '809U'},
 {'category': 'Words', 'cn': '全景式天幕', 'en': 'Panoramic roof', 'note': '416'},
 {'category': 'Words', 'cn': '星辰轨迹 / 矩阵星轨 /星驰光轨 / 璀璨星轨 贯穿式尾灯', 'en': 'Rear light strip', 'note': '329'},
 {'category': 'Words', 'cn': '冷空灰', 'en': 'tech grey', 'note': '108A'},
 {'category': 'Words', 'cn': 'MBUX.超感屏 / MBUX.超级屏', 'en': 'Driver display', 'note': '458'},
 {'category': 'Words',
  'cn': '嵌铝质饰条的棕色开孔型橡木饰条',
  'en': "Ship's deck open-pore brown oak trim elements with aluminium lines",
  'note': '17H'},
 {'category': 'Words', 'cn': '灰色开孔型桦木木饰条', 'en': 'Open-pore grey birch wood trim elements', 'note': '18H'},
 {'category': 'Words',
  'cn': '哑光白色暗纹天然纤维饰条',
  'en': 'Matt white natural fibre silent lines trim elements',
  'note': '19H'},
 {'category': 'Words', 'cn': 'MB.Drive辅助驾驶', 'en': 'Digital Extra: MB.DRIVE ASSIST', 'note': 'P20'},
 {'category': 'Words', 'cn': 'MB.Drive辅助驾驶Pro', 'en': 'Digital Extra: MB.DRIVE ASSIST PRO', 'note': 'PAB'},
 {'category': 'Words', 'cn': '沉浸式导航', 'en': 'Digital Extra: MBUX Navigation', 'note': '365'},
 {'category': 'Words', 'cn': '沉浸式导航', 'en': 'MBUX Surround Navigation', 'note': None},
 {'category': 'Words',
  'cn': '梅赛德斯-奔驰电动智能导航',
  'en': 'Mercedes-Benz Navigation with Electric Intelligence',
  'note': None},
 {'category': 'Words', 'cn': '驻车守护', 'en': 'Digital Extra: GUARD 360° vehicle protection plus', 'note': 'PBK'},
 {'category': 'Words', 'cn': '银色声浪', 'en': '1. Silver Waves', 'note': 'Sounds'},
 {'category': 'Words', 'cn': '灵动之流', 'en': '2. Vivid Flux', 'note': None},
 {'category': 'Words', 'cn': '和煦清风', 'en': '3. Serene Breeze', 'note': None},
 {'category': 'Words', 'cn': '声灵幻境', 'en': '4. Fractal Fusion', 'note': None},
 {'category': 'Words', 'cn': '纵声天地', 'en': '5. Granular Fuzz', 'note': None},
 {'category': 'Words', 'cn': '全新纯电GLB', 'en': 'GLB with EQ Technology', 'note': 'X244'},
 {'category': 'Words', 'cn': '全新GLB', 'en': 'GLB', 'note': 'X248'},
 {'category': 'Words', 'cn': '全新纯电GLA', 'en': 'GLA with EQ Technology', 'note': 'H244'},
 {'category': 'Words', 'cn': '全新GLA', 'en': 'GLA', 'note': 'H248'},
 {'category': 'Words', 'cn': '全新纯电长轴距C级车', 'en': 'C-Class L with EQ Technology', 'note': 'V520'},
 {'category': 'Words', 'cn': '全新纯电长轴距GLC SUV', 'en': 'GLC L with EQ Technology', 'note': 'V540'},
 {'category': 'Words', 'cn': '高速领航辅助驾驶', 'en': 'Highway NGA', 'note': None},
 {'category': 'Words', 'cn': '城区领航辅助驾驶', 'en': 'City NGA', 'note': None},
 {'category': 'Words', 'cn': '霁青', 'en': 'Dynastic Glaze', 'note': 'MANUFAKTUR mystic blue metalic'},
 {'category': 'Words', 'cn': '玄黑', 'en': 'Enigma night', 'note': 'MANUFAKTUR night black magno'},
 {'category': 'Words', 'cn': '栾华', 'en': 'Venerable goldrain tree', 'note': 'MANUFAKTUR kalahari gold magno'},
 {'category': 'Words', 'cn': '月白', 'en': 'Lunar brilliance', 'note': 'MANUFAKTUR vintage blue solid'},
 {'category': 'Words', 'cn': '发光梅赛德斯-奔驰星标', 'en': 'Illuminated Mercedes star', 'note': '24U'},
 {'category': 'Words', 'cn': '晴空蓝色', 'en': 'Clear blue', 'note': '809U'},
 {'category': 'Words', 'cn': 'MBUX超级屏', 'en': 'Driver display', 'note': '458'},
 {'category': 'Words',
  'cn': '嵌铝质饰条的棕色开孔型橡木饰条',
  'en': "Ship's deck open-pore brown oak trim elements with aluminum lines",
  'note': '17H'},
 {'category': 'Words', 'cn': '灰色开孔型桦木木饰条', 'en': 'Open-pore grey birch wood trim elements', 'note': '18H'},
 {'category': 'Words',
  'cn': '哑光白色暗纹天然纤维饰条',
  'en': 'Matt white natural fiber silent lines trim elements',
  'note': '19H'},
 {'category': 'Words', 'cn': '沉浸式导航', 'en': 'Digital Extra: MBUX Navigation', 'note': '365'},
 {'category': 'Words', 'cn': '驻车守护', 'en': 'Digital Extra: GUARD 360° vehicle protection plus', 'note': 'PBK'},
 {'category': 'Words', 'cn': '冷空灰', 'en': 'tech grey', 'note': '108A'},
 {'category': 'Words', 'cn': '雾灰绿色 / 雾灰蓝色', 'en': 'aqua-mint non-metallic', 'note': '341U'},
 {'category': 'Words', 'cn': '全景式天幕', 'en': 'Panoramic roof', 'note': '416'},
 {'category': 'Words', 'cn': '银色声浪', 'en': '1. Silver Waves', 'note': 'Sounds'},
 {'category': 'Words', 'cn': '灵动之流', 'en': '2. Vivid Flux', 'note': None},
 {'category': 'Words', 'cn': '和煦清风', 'en': '3. Serene Breeze', 'note': None},
 {'category': 'Words', 'cn': '声灵幻境', 'en': '4. Fractal Fusion', 'note': None},
 {'category': 'Words', 'cn': '纵声天地', 'en': '5. Granular Fuzz', 'note': None},
 {'category': 'Words', 'cn': '星徽之幕封闭式格栅', 'en': 'Panel with illuminated Mercedes-Benz pattern', 'note': '4B7'},
 {'category': 'Words', 'cn': '星流之翼贯穿式尾灯', 'en': 'Rear light strip', 'note': '329'},
 {'category': 'Words', 'cn': 'MB.Drive辅助驾驶', 'en': 'Digital Extra: MB.DRIVE ASSIST', 'note': 'P20'},
 {'category': 'Words', 'cn': 'MB.Drive辅助驾驶Pro', 'en': 'Digital Extra: MB.DRIVE ASSIST PRO', 'note': 'PAB'},
 {'category': 'Words', 'cn': '星徽光漩', 'en': '尾灯', 'note': None},
 {'category': 'Words', 'cn': '星徽之瞳', 'en': '前灯', 'note': None},
 {'category': 'Words', 'cn': '全新纯电CLA', 'en': 'The Electric CLA', 'note': None},
 {'category': 'Words', 'cn': '全新纯电CLA 300 L', 'en': 'CLA 300 L', 'note': None},
 {'category': 'Words', 'cn': '全新纯电CLA 260 L', 'en': 'CLA 260 L', 'note': None},
 {'category': 'Words', 'cn': '纯电CLA 300 L 超长续航领智版', 'en': 'CLA 300 L Style', 'note': None},
 {'category': 'Words', 'cn': '纯电CLA 300 L 超长续航版', 'en': 'CLA 300 L Dynamic', 'note': None},
 {'category': 'Words', 'cn': '纯电 CLA 300 L 超长续航冠军版', 'en': "CLA 300 L Champion's Edition", 'note': None},
 {'category': 'Words',
  'cn': '嵌铝质饰条的棕色开孔型橡木饰条',
  'en': "Ship's deck open-pore brown oak trim elements with aluminum lines",
  'note': '17H'},
 {'category': 'Words', 'cn': '发光梅赛德斯-奔驰星标', 'en': 'Illuminated Mercedes star', 'note': '24U'},
 {'category': 'Words', 'cn': '沉浸式导航', 'en': 'Digital Extra: MBUX Navigation', 'note': '365'},
 {'category': 'Words', 'cn': '全景式天幕', 'en': 'Panoramic roof', 'note': '416'},
 {'category': 'Words', 'cn': '全数字仪表盘显示屏', 'en': 'Driver display', 'note': '458'},
 {'category': 'Words', 'cn': '前排乘客显示屏', 'en': 'MBUX Superscreen', 'note': '860'},
 {'category': 'Words', 'cn': '冷空灰', 'en': 'tech grey', 'note': '108A'},
 {'category': 'Words', 'cn': '驾驶员无响应紧急停车', 'en': 'Emergency stop function with lane change', 'note': 'K41'},
 {'category': 'Words', 'cn': '侧面盲点辅助', 'en': 'Blind Spot Assist', 'note': 'K53'},
 {'category': 'Words', 'cn': '自动紧急制动', 'en': 'Brake Assist', 'note': 'K57'},
 {'category': 'Words', 'cn': '紧急转向辅助', 'en': 'Evasive steering function', 'note': 'K59'},
 {'category': 'Words', 'cn': '倒车影像', 'en': 'Reversing Camera', 'note': 'K62'},
 {'category': 'Words', 'cn': '侧面盲点辅助增强版', 'en': 'Blind Spot Assist Plus', 'note': 'K64'},
 {'category': 'Words', 'cn': '车道居中', 'en': 'Digital Extra: Steering Assist', 'note': 'K65'},
 {'category': 'Words', 'cn': '驻车定位系统', 'en': 'Digital Extra: PARKTRONIC', 'note': 'K69'},
 {'category': 'Words', 'cn': '智能泊车', 'en': 'Digital Extra: Parking Assist', 'note': 'K70'},
 {'category': 'Words', 'cn': '循迹倒车功能', 'en': 'Digital Extra: Reverse maneuvering function', 'note': 'K71'},
 {'category': 'Words', 'cn': '360°摄像头', 'en': 'Digital Extra: 360° camera', 'note': 'K72'},
 {'category': 'Words', 'cn': '车载娱乐应用', 'en': 'Pre-installation for MBUX Entertainment Advanced', 'note': '04W'},
 {'category': 'Words', 'cn': '前备箱', 'en': 'Frunk', 'note': '3K1'},
 {'category': 'Words', 'cn': '面部识别', 'en': 'Facial recognition', 'note': '46U'},
 {'category': 'Words', 'cn': '数字化产品和服务', 'en': 'Pre-installation for Digital Extras', 'note': '4U1'},
 {'category': 'Words', 'cn': '智能人机交互系统', 'en': 'MBUX Multimedia system premium++', 'note': '530'},
 {'category': 'Words', 'cn': '限速功能', 'en': 'Digital Extra: speed limit function', 'note': '546'},
 {'category': 'Words', 'cn': '直流充电系统', 'en': 'Direct current charging system', 'note': '693'},
 {'category': 'Words', 'cn': '车内乘员监测', 'en': 'Active rear passenger presence detection', 'note': 'B19'},
 {'category': 'Words', 'cn': '远程服务', 'en': 'Pre-installation for MB.CONNECT Package', 'note': 'U0C'},
 {'category': 'Words', 'cn': '星迹相随贯穿式尾灯', 'en': 'Rear light strip', 'note': '329'},
 {'category': 'Words', 'cn': '星心相息封闭式格栅', 'en': 'Panel with illuminated Mercedes-Benz pattern', 'note': '4B7'},
 {'category': 'Words', 'cn': '星徽之瞳', 'en': '前车灯', 'note': None},
 {'category': 'Words', 'cn': '星徽光漩', 'en': '后车灯', 'note': None},
 {'category': 'Words', 'cn': '素纹植纤维饰条', 'en': 'Matt white natural fiber silent lines trim elements', 'note': '19H'},
 {'category': 'Words', 'cn': '水韵青', 'en': 'aquamarine blue metallic', 'note': '341U'},
 {'category': 'Words', 'cn': 'L2+', 'en': '导航辅助驾驶', 'note': '如E-Class, C-Class, GLC SUV'},
 {'category': 'Words',
  'cn': 'L2+ Highway Intelligent Assisted Driving',
  'en': '高速领航辅助驾驶',
  'note': '如CLA L, 未上市的S-Class FL及未来MBEA.M等车型'},
 {'category': 'Words', 'cn': 'L2++ Urban & Highway Intelligent Assisted Driving', 'en': '城区及高速领航辅助驾驶', 'note': '完整版'},
 {'category': 'Words', 'cn': 'MB.Drive辅助驾驶Pro', 'en': 'Digital Extra: MB.DRIVE ASSIST PRO', 'note': None},
 {'category': 'Words', 'cn': 'MB.Drive辅助驾驶', 'en': 'Digital Extra: MB.DRIVE ASSIST', 'note': None},
 {'category': 'Words', 'cn': 'R6强化学习大模型', 'en': 'R6 Reinforcement Learning Large Model', 'note': None},
 {'category': 'Words', 'cn': '温特图尔克海姆', 'en': 'Untertürkheim', 'note': None},
 {'category': 'Words', 'cn': '“人机共驾”', 'en': '‘Cooperative Steering’', 'note': None},
 {'category': 'Words', 'cn': '循迹倒车', 'en': 'Retrace Maneuver Assist (RMA)', 'note': None},
 {'category': 'Words', 'cn': '智能泊车 （全新一代）', 'en': 'Automatic Parking Assist (APA)', 'note': None},
 {'category': 'Words', 'cn': '记忆泊车', 'en': 'MVA', 'note': None},
 {'category': 'Words', 'cn': '油电同智', 'en': 'ICEs and NEVs sharing the same intelligence', 'note': None}]

# Media name lookups
MB_MEDIA_CN_TO_EN = {'车闻社': 'Auto Press',
 '网通社': 'Internet Info Agency',
 '车主指南': 'ICAUTO',
 '汽车之家': 'Autohome',
 '易车': 'Yiche',
 '大话车江湖': 'AUTO JIANGHU',
 '此地无垠': 'ABVideo',
 '超级充电站': 'SUPERCHARGED',
 '大家车言论': 'djcars',
 '新出行': 'XCHUXING.COM',
 'PS3保罗': 'Cars01',
 '汽车预言家': 'Car Prophet',
 '汽车十三行': 'Full chain Car',
 '超电实验室': 'SuperEV-Lab',
 '萝卜报告': 'LOBO REPORT',
 '42号车库': '42HOW',
 '懂车帝': 'Dcar',
 '钛媒体': 'TMTpost',
 '电动星球': 'EV Planet',
 '电动汽车观察家': 'Evobserver',
 '汽车书场': 'Auto Storytelling',
 '盖世汽车': 'Gasgoo'}
MB_MEDIA_EN_TO_CN = {'Auto Press': '车闻社',
 'Internet Info Agency': '网通社',
 'ICAUTO': '车主指南',
 'Autohome': '汽车之家',
 'Yiche': '易车',
 'AUTO JIANGHU': '大话车江湖',
 'ABVideo': '此地无垠',
 'SUPERCHARGED': '超级充电站',
 'djcars': '大家车言论',
 'XCHUXING.COM': '新出行',
 'Cars01': 'PS3保罗',
 'Car Prophet': '汽车预言家',
 'Full chain Car': '汽车十三行',
 'SuperEV-Lab': '超电实验室',
 'LOBO REPORT': '萝卜报告',
 '42HOW': '42号车库',
 'Dcar': '懂车帝',
 'TMTpost': '钛媒体',
 'EV Planet': '电动星球',
 'Evobserver': '电动汽车观察家',
 'Auto Storytelling': '汽车书场',
 'Gasgoo': '盖世汽车'}

# Executive / spokesperson lookup (lightly cleaned)
MB_EXECUTIVES = [{'en_name': 'Ola Källenius',
  'cn_name': '康林松先生',
  'en_title': 'Chairman of the Board of Management of Mercedes-Benz Group AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会主席'},
 {'en_name': 'Ms. Britta Seeger',
  'cn_name': '贝思格女士',
  'en_title': 'Member of the Board of Management of Mercedes-Benz Group AG, responsible for Human Resources and Labor '
              'Director',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会成员，负责人力资源及劳动关系'},
 {'en_name': 'Mathias Geisen',
  'cn_name': '盖森',
  'en_title': 'Member of the Board of Management of Mercedes‑Benz Group AG. Sales & Customer Experience Marketing',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会成员，负责销售与客户体验 市场营销'},
 {'en_name': 'Jörg Burzer',
  'cn_name': '白韫泽',
  'en_title': 'Member of the Board of Management of Mercedes-Benz Group AG. Chief Technology Officer, Development & '
              'Procurement Markus Schäfer Non-Executive Chairman of the Board Mercedes-AMG PETRONAS F1 Team',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会成员及首席技术官，负责研发和采购 薛夫铭先生 梅赛德斯-AMG马石油F1车队非执行董事会主席'},
 {'en_name': 'Bastian Baudy',
  'cn_name': '鲍迪',
  'en_title': 'Chief Design Officer of Mercedes-Benz Group AG Gorden Wagener',
  'cn_title': '梅赛德斯-奔驰集团股份公司首席设计官 瓦格纳'},
 {'en_name': 'Magnus Östberg',
  'cn_name': '欧孟宇先生',
  'en_title': 'Chief Software Officer at Mercedes‑Benz Group AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司首席软件官'},
 {'en_name': 'Michael Schiebe',
  'cn_name': '沈明轩',
  'en_title': 'Member of the Board of Management of Mercedes-Benz Group AG, responsible for Production, Quality and '
              'Supply Chain Management',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会成员，负责生产、品质与供应链'},
 {'en_name': 'Jochen Hermann',
  'cn_name': '约亨·赫曼先生',
  'en_title': 'Member of Management of Mercedes-AMG GmbH, Chief Technical Officer/Technical General Manager of '
              'Mercedes-AMG GmbH',
  'cn_title': '梅赛德斯-AMG有限责任公司董事会成员、首席技术官/梅赛德斯-AMG技术研发总经理'},
 {'en_name': 'Oliver Thöne',
  'cn_name': '佟欧福',
  'en_title': 'Member of the Board of Management of Mercedes-Benz Group AG, responsible for Greater China Hubertus '
              'Troska',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会成员、负责大中华区业务 唐仕凯先生'},
 {'en_name': 'Daniel Lescow',
  'cn_name': '李德思',
  'en_title': 'President & CEO, Beijing Mercedes-Benz Sales Service Co. Ltd. Fred Duan',
  'cn_title': '北京梅赛德斯-奔驰销售服务有限公司总裁兼首席执行官 段建军'},
 {'en_name': 'Andy Zhang',
  'cn_name': '张焱先生',
  'en_title': 'Senior Executive Vice President of Beijing Mercedes-Benz Sales Service Co., Ltd. Chairman of '
              'Mercedes-Benz Star Fund Management Committee',
  'cn_title': '北京梅赛德斯-奔驰销售服务有限公司高级执行副总裁 梅赛德斯-奔驰星愿基金管理委员会主席'},
 {'en_name': 'Oliver Britz',
  'cn_name': '毕立思',
  'en_title': 'Executive Vice President of Sales of Beijing Mercedes-Benz Sales Service Co., Ltd.',
  'cn_title': '北京梅赛德斯-奔驰销售服务有限公司销售执行副总裁'},
 {'en_name': '周娟', 'cn_name': '赵筠舒', 'en_title': '北京梅赛德斯-奔驰销售服务有限公司数字化与传播副总裁', 'cn_title': '北京梅赛德斯-奔驰销售服务有限公司品牌与传播总监'},
 {'en_name': '沈爱琪',
  'cn_name': '毕云凡',
  'en_title': '北京梅赛德斯-奔驰销售服务有限公司传播与市场营销部高级经理',
  'cn_title': '北京梅赛德斯-奔驰销售服务有限公司传播与市场营销部高级经理 毕柳帆'},
 {'en_name': 'Ms. Jasmin Eichler',
  'cn_name': '雅斯敏·艾希勒女士',
  'en_title': 'Director of Future Technology at Mercedes-Benz',
  'cn_title': '梅赛德斯-奔驰集团股份公司未来技术研究部门负责人'},
 {'en_name': 'Adam Allsopp',
  'cn_name': '亚当·奥尔索普先生',
  'en_title': 'Advanced Technology Director of Mercedes‑AMG High Performance Powertrains',
  'cn_title': '梅赛德斯-AMG高性能动力系统有限公司前沿技术总监'},
 {'en_name': 'Ms. Joana Jarisch', 'cn_name': '乔安娜·贾里希女士', 'en_title': '', 'cn_title': '梅赛德斯-奔驰集团股份公司色彩与内饰概念负责人'},
 {'en_name': 'Ms. Bettina Fetzer',
  'cn_name': '贝蒂娜·费泽尔女士',
  'en_title': 'Vice President Communications & Marketing Mercedes-Benz Group AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司传播与市场营销副总裁'},
 {'en_name': 'Harald Wilhelm',
  'cn_name': '文海铎',
  'en_title': 'Member of the Board of Management of Mercedes-Benz Group AG, responsible for Finance',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会成员及首席财务官'},
 {'en_name': 'Oliver Löcher',
  'cn_name': '欧立甫',
  'en_title': 'Vice President Vehicle Engineering and Overall Vehicle Functions Mercedes-Benz Cars Christoph '
              'Starzynski',
  'cn_title': '梅赛德斯-奔驰集团股份公司车辆工程及整车功能副总裁 克里斯托夫·斯塔津斯基'},
 {'en_name': 'Adam Allsopp',
  'cn_name': '亚当·奥尔索普',
  'en_title': "Mercedes-AMG HPP's Advanced Technology Director",
  'cn_title': '梅赛德斯-AMG高性能动力部门前沿技术总监'},
 {'en_name': '周宁女士',
  'cn_name': 'Chris Fu',
  'en_title': '北京梅赛德斯-奔驰销售服务有限公司客户服务执行副总裁',
  'cn_title': 'Director of Sales Management of Beijing Mercedes-Benz Sales Service Co., Ltd.'},
 {'en_name': 'Prof. Dr. Hans George Engel',
  'cn_name': '安尔翰博士教授',
  'en_title': 'Senior Executive Vice President of Mercedes-Benz Group China Ltd., Head of Mercedes-Benz China Product '
              'and Project Steering, Industrialization & Cooperation Management',
  'cn_title': '梅赛德斯-奔驰（中国）投资有限公司高级执行副总裁，产品及项目控制，工业化与合作管理负责人'},
 {'en_name': 'Matthias Klöpfer', 'cn_name': '马蒂亚斯·科普费尔', 'en_title': '', 'cn_title': '梅赛德斯-奔驰混合动力技术研发工程师'},
 {'en_name': 'Steffen Hoffmann',
  'cn_name': '何甫曼',
  'en_title': 'Head of Treasury and Investor Relations of Mercedes-Benz Group AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司司库和投资者关系负责人'},
 {'en_name': 'Olaf Schick',
  'cn_name': '时琨',
  'en_title': 'Member of the Board of Management of Mercedes-Benz Group AG, responsible for Integrity and Legal '
              'Affairs',
  'cn_title': '梅赛德斯-奔驰集团股份公司董事会成员，负责诚信与法律事务'},
 {'en_name': 'Birgit Klockenhoff',
  'cn_name': '波吉特·克洛肯霍夫',
  'en_title': 'Project Lead Future Sustainable Materials, Mercedes-Benz Group AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司未来可持续材料项目负责人'},
 {'en_name': 'Drummond Jacoy',
  'cn_name': '庄睦德',
  'en_title': 'Senior Executive Vice President of Mercedes-Benz Group China Ltd., Head of Mercedes-Benz China '
              'Research, Development and Procurement',
  'cn_title': '梅赛德斯-奔驰（中国）投资有限公司高级执行副总裁，梅赛德斯-奔驰中国研发和采购负责人'},
 {'en_name': 'Jörg Bartels',
  'cn_name': '柏睿凯',
  'en_title': 'President & CEO, Beijing Benz Automotive Co., Ltd. (BBAC)',
  'cn_title': '北京奔驰汽车有限公司总裁兼首席执行官 26.5.1接任Torsten Eder'},
 {'en_name': 'Wang Xin',
  'cn_name': '王忻',
  'en_title': 'Executive Vice President of Mercedes-Benz Group China Ltd., responsible for Mercedes-Benz R&D China '
              'Automated Driving and Connectivity',
  'cn_title': '梅赛德斯-奔驰（中国）投资有限公司执行副总裁，梅赛德斯-奔驰中国研发自动驾驶及车联网负责人'},
 {'en_name': 'Michael He',
  'cn_name': '何阔',
  'en_title': 'General Manager of Region North, Beijing Mercedes-Benz Sales Service Co. Ltd.',
  'cn_title': '北京梅赛德斯-奔驰销售服务有限公司北区总经理'},
 {'en_name': 'David Vorsteher',
  'cn_name': '方达惟',
  'en_title': 'Head of TEV Sales China of Mercedes-Benz (China) Sales Limited Ralf Eisenreich',
  'cn_title': '梅赛德斯-奔驰TEV销售中国区负责人 负责梅赛德斯-AMG、G级越野车和梅赛德斯-迈巴赫 阮森海'},
 {'en_name': 'Konstantin Neiß',
  'cn_name': '康斯坦丁·奈斯',
  'en_title': 'Head of Development Electric Drive Units at Mercedes-Benz Chairman of YASA Motors',
  'cn_title': '梅赛德斯-奔驰集团股份公司 动力系统与电力驱动部门研发负责人 YASA电机公司 董事长'},
 {'en_name': 'Jan Brecht',
  'cn_name': '扬·布雷希特',
  'en_title': 'Chief Information Officer (CIO) of Mercedes-Benz Group AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司首席信息官'},
 {'en_name': 'Joel Baek',
  'cn_name': '白哲旼',
  'en_title': 'Head of Design, Mercedes-Benz China',
  'cn_title': '梅赛德斯-奔驰中国设计中心负责人'},
 {'en_name': '吕汉超',
  'cn_name': '顾星宇',
  'en_title': '梅赛德斯-奔驰中国研发中心 MBUX智能座舱和车联网研发总监',
  'cn_title': '梅赛德斯-奔驰中国研发中心MBUX智能座舱和车联网研发'},
 {'en_name': '袁睿', 'cn_name': '史高磊', 'en_title': '梅赛德斯-奔驰中国研发中心MBUX智能座舱和车联网研发', 'cn_title': '梅赛德斯-奔驰智能驾驶辅助系统高级工程师'},
 {'en_name': 'Moritz Kilper',
  'cn_name': '莫里茨·科珀',
  'en_title': 'Development of Electric Motors for High Performance Drive Unit AMG.EA',
  'cn_title': 'AMG.EA平台电机研发工程师'},
 {'en_name': 'Adam Brant',
  'cn_name': '亚当·布兰特',
  'en_title': 'Project Manager E Motors at YASA',
  'cn_title': 'YASA电机项目负责人'},
 {'en_name': 'Jochen Schmitz',
  'cn_name': '约亨·施密茨',
  'en_title': 'Head of Operation for the Hybrid Strategy at Mercedes-AMG',
  'cn_title': '梅赛德斯-AMG高性能混动策略研发负责人'},
 {'en_name': 'Dr. Martin Brudenmüller',
  'cn_name': '薄睦乐',
  'en_title': 'Chairman of the Supervisory Board of Mercedes-Benz Group AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司监事会主席'},
 {'en_name': 'Thomas Klein',
  'cn_name': '柯孟林',
  'en_title': 'Head of Mercedes‑Benz Vans',
  'cn_title': '梅赛德斯-奔驰商务车全球业务负责人'},
 {'en_name': 'Dr. Andreas Zygan',
  'cn_name': '安德烈亚斯·齐根博士',
  'en_title': 'Head of Development Mercedes-Benz Vans, Mercedes-Benz AG',
  'cn_title': '梅赛德斯-奔驰集团股份公司商务车研发负责人'},
 {'en_name': 'Johann Buss',
  'cn_name': '白岳涵',
  'en_title': 'Executive Vice President of Mercedes-Benz Group China Ltd., responsible for Mercedes-Benz R&D Vehicle '
              'Integration, Body, Safety & Tech Center China',
  'cn_title': '梅赛德斯-奔驰（中国）投资有限公司执行副总裁，梅赛德斯-奔驰整车集成、车身、安全与研发技术中心负责人'},
 {'en_name': '张瀚淳', 'cn_name': '黄尔宇', 'en_title': '北京梅赛德斯-奔驰销售服务有限公司产品专家', 'cn_title': '北京梅赛德斯-奔驰销售服务有限公司整车动力性经济性工程师'},
 {'en_name': '陶智健',
  'cn_name': '姚颖',
  'en_title': '北京梅赛德斯-奔驰销售服务有限公司产品管理部数字化产品专家',
  'cn_title': '北京梅赛德斯-奔驰销售服务有限公司充电与高压系统测试经理'},
 {'en_name': 'Marcus Breitschwerdt',
  'cn_name': '马库斯·布雷特施韦德特',
  'en_title': 'Executive Vice President of Mercedes-Benz AG and CEO of Mercedes-Benz Heritage GmbH',
  'cn_title': '梅赛德斯-奔驰集团股份公司执行副总裁、梅赛德斯-奔驰经典车业务负责人'}]

# Recommended PR normalization rules (starter pack)
MB_NORMALIZE_RULES = {
    "奔驰": "梅赛德斯-奔驰",
    "德国时间": "欧洲中部时间（CET）",
    "中国时间": "北京时间（UTC+8）",
    "北京时间": "北京时间（UTC+8）",
    "新车": "全新车型",
}

def normalize_with_mb_terms(text: str) -> str:
    """Apply a small set of deterministic PR normalization rules.
    Keep this conservative: do not auto-replace all terms blindly.
    """
    for wrong, official in MB_NORMALIZE_RULES.items():
        text = text.replace(wrong, official)
    return text

def find_non_official_cn_terms(text: str) -> list[tuple[str, str]]:
    """Return [(matched_cn, official_en)] for Chinese official terms found in text."""
    hits = []
    for cn, en in MB_CN_TO_EN.items():
        if cn in text:
            hits.append((cn, en))
    return hits

def find_non_official_en_terms(text: str) -> list[tuple[str, str]]:
    """Return [(matched_en, official_cn)] for English official terms found in text."""
    hits = []
    for en, cn in MB_EN_TO_CN.items():
        if en in text:
            hits.append((en, cn))
    return hits
